[project]
name = 'Tokenized-Equipment-Leasing-for-Construction'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.asset-registration]
path = 'contracts/asset-registration.clar'
clarity_version = 2
epoch = 2.5

[contracts.lessee-verification]
path = 'contracts/lessee-verification.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
